language: node_js

notifications:
  email:
    - eward.song@gmail.com

node_js:
  - 0.10

install:
  - npm install mocha-phantomjs phantomjs
  - npm install mocha

script:
  - mocha-phantomjs 1.0.1/spec/index.html -t 40000 -R dot
